[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
adapter = "EUDyxkHVf9NBRTREn69rcFDAEefmHj3UrLJV14vnqACp"
debridge-reporter = "7GPwvvhq33fTYuDyfA1JVz4fp3XkdcmjerJWpUkxjrC2"
hashi = "76cEKq1qRhBLn56kZdG1Hj7UHXggcNfinbnKejXDnMpU"
wormhole-reporter = "3ESz1nYWmkdp9A3SByK7mbf9toDSRPvJADDF6pz45qZG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

### Wormhole Core Bridge
[[test.validator.clone]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"

### Wormhole Bridge
[[test.validator.clone]]
address = "2yVjuQwpsvdsrywzsJJVs9Ueh4zayyo5DYJbBNc3DDpn"

### Wormhole Fee Collector
[[test.validator.clone]]
address = "9bFNrXNb2WTx8fMHXCheaZqkLZ3YCCaiqTftHxeintHy"