[package]
name = "debridge-reporter"
version = "0.1.0"
description = "Debridge reporter"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "debridge_reporter"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
debridge-solana-sdk = "1.0.1"
slots = { path = "../../shared/slots" }